options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/dart-lang/flutter'
    entrypoint: bash
    args:
      - -c
      - |
        flutter --version
        flutter pub get
        flutter build web --release

timeout: '1200s'
