steps:
  - name: 'cirrusci/flutter:3.24.3'
    entrypoint: bash
    args:
      - -c
      - |
        flutter pub get
        flutter build web --release
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY